plugins {
    id 'base'
}

group = 'pl.tomaszmiller'
version = '2.0.0-SNAPSHOT'
description = 'Alexandria – library management application.'

ext {
    javafxVersion        = '23.0.2'
    mysqlVersion         = '9.1.0'
    sqliteVersion        = '3.47.2.0'
    hikaricpVersion      = '6.2.1'
    slf4jVersion         = '2.0.17'
    logbackVersion       = '1.5.18'
    junitVersion         = '5.12.2'
    junitPlatformVersion = '1.12.2'
    jbcryptVersion       = '0.4'
    gsonVersion          = '2.11.0'
    h2Version            = '2.3.232'
    mockitoVersion       = '5.15.2'
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'checkstyle'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    checkstyle {
        toolVersion = '10.21.1'
        configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
        ignoreFailures = true
    }
}
